### ISSUE TITLE
RAM Register for ESS Grid SetPoint

### ISSUE THREAD

**Issue by ErmaEnergy** [yvesf/ve-ctrl-tool#1]
Hi Yves,

And thanks for your work. I am struggling to command the electricity injection with MK2 with the ESS mode activated on the inverter. On your soft, you write a setpoint on RAM ID 129, but on my side, after trying, it seems to be on ID 131. Where did you get the information about RAM ID description ? 
FYI RAM ID 136 is the maximum PV Feed IN (in Watt).

Also, without Venus-OS device connected, the Ve.Bus device goes into "Pass-Thru" mode after 4 min. Any idea which register is needed to maintain the Inverter ON ?

Thanks a lot in advance

Best regards

**Comment by yvesf** [comment]
Hi @Danakil23 !

Yes you're right, on some inverters it's 129 and on others 131, apparently. I also posted about it here: https://community.victronenergy.com/questions/129947/problem-implementing-the-example-364-from-the-ess.html?childToView=171312#comment-171312

I got the RAM ID from the Victron documentation and for the small multiplus it was correct. 
In the code I made a change to first discover the ESS RAM Id before writing to it, haven't pushed it yet to github but I'll do soon.

<details>
  <summary>mk2ess.go</summary>

```go
type Mk2ESS struct {
	mk2            *Mk2
	assistantRamID uint16
}

// ESSInit searches for the ESS Assistent in RAM
// if not found returns with error.
func ESSInit(ctx context.Context, mk2 *Mk2) (*Mk2ESS, error) {
	// 200 is arbitrary chosen upper bound.
	// should be corrected if information is available.
	for i := 128; i < 200; i++ {
		log.Debug().Int("ramID", i).Msg("probing ramid")
		low, high, _, _, err := mk2.CommandReadRAMVar(ctx, byte(i), 0)
		if err != nil {
			return nil, fmt.Errorf("failed to enumerate ESS assistent ram records: %w", err)
		}
		if high == 0x0 && low == 0x0 {
			log.Debug().Msg("found end of ramIDs in use")
			break
		}

		assistantID := (uint16(high)<<8 | uint16(low)) >> 4
		log.Debug().Int("assistantID", int(assistantID)).Msg("id")
		if assistantID == 5 {
			return &Mk2ESS{
				mk2:            mk2,
				assistantRamID: uint16(i),
			}, nil
		}

		// this is not the ESS record, jump to next block
		i += int(low & 0xf)
	}

	return nil, fmt.Errorf("ESS RAM Record not found")
}

func (m *Mk2ESS) SetpointSet(ctx context.Context, value int16) error {
	log.Info().Int("value", int(value)).Int("record", int(m.assistantRamID)).Msg("write setpoint")
	return m.mk2.CommandWriteRAMVarDataSigned(ctx, m.assistantRamID+1, value)
}
```

</details>

I can't say anything about Venus-OS, so far I was operating the Multiplus just with my program directly. You probably know already that you have to keep sending to the ESS RAM-Register (something between 5-30s, don't know exactly). This is what the `ess-static` command is for.

Thanks for mentioning the PV Feed-IN. Generally interesting would be to document the RAM-Identifier (the length-and ID field before the fields). Maybe you could share all your RAM IDs values similiar to what I did in the forum?

Best regards, yves

**Comment by ErmaEnergy** [comment]
Hi @yvesf,
What a nice piece of code to detect the grid setpoint RAM ID ! Thanks
About my problem, that the inverter goes into "Pass Thru" mode, i found out it was because of a "low battery voltage" alarm (even tho my voltage was above the cut-off voltage). It seems that the ESS assistant has a problem in a calculation of the sustain voltage + restart voltage without Venus OS running (I used a venus OS in parallel of the RS485, to check what RAM was used). For now, I just dropped the sustain voltage to a very low value and the problem disappear, but I'll investigate further later.

One last question: On what documentation did you find the setpoint RAM ID ? On my side I used the "Interfacing with VE.Bus products - MK2 protocol" and it describes RAM ID up to ID 19 only. Also I asked Victron directly about how to manage grid setpoint and they refuse to give me the solution, for them it's only allowed through Modbus-TCP.

Best regards

**Comment by yvesf** [comment]
@Danakil23 https://www.victronenergy.com/live/ess:ess_mode_2_and_3

> Writing the set point with +200 Watt:
> We should write RAM ID 129 to +200. Writing requires 2 frames, one frame specifying the ID to write and one frame specifying the data to write.
